"""Interface every infrastructure backend (simulated or real) must implement."""

from typing import Any, Protocol


class InfrastructureBackend(Protocol):
    def get_logs(self, service: str) -> list[str]: ...

    def get_metrics(self, service: str) -> dict[str, float]: ...

    def get_recent_deployments(self, service: str) -> list[dict[str, Any]]: ...

    def get_service_status(self, service: str) -> dict[str, Any]: ...

    def restart_service(self, service: str) -> str: ...

    def rollback_deployment(self, service: str) -> str: ...
